import { useState, useEffect } from "react";
import {
  View, Text, TextInput, StyleSheet, ScrollView, Alert,
  TouchableOpacity, Switch, ActivityIndicator, Modal,
} from "react-native";
import { useRouter, useLocalSearchParams } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as MailComposer from "expo-mail-composer";
import { WebView } from "react-native-webview";
import { supabase } from "@core/network";
import { formRepository } from "@features/forms/repositories/FormRepository";
import { colors, spacing, borderRadius, fontSize } from "@shared/theme";
import { PressableScale } from "@shared/components/PressableScale";
import { formatDateStr, getCalendarDays, MONTH_NAMES } from "@shared/utils";
import { QRShareModal } from "@shared/components/QRShareModal";

interface FormField {
  id: string;
  label: string;
  type: "text" | "textarea" | "number" | "select" | "checkbox";
  options?: string[];
  required?: boolean;
  placeholder?: string;
}

interface FormSection {
  title: string;
  fields: FormField[];
}

export default function FormEditorScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();

  const [formData, setFormData] = useState<Record<string, unknown>>({});
  const [sections, setSections] = useState<FormSection[]>([]);
  const [templateName, setTemplateName] = useState("");
  const [formStatus, setFormStatus] = useState("draft");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    loadForm();
  }, [id]);

  async function loadForm() {
    if (!id) return;
    setLoading(true);
    try {
      const result = await formRepository.findById(id);
      if (!result.success) {
        Alert.alert("Error", result.error.message);
        router.back();
        return;
      }

      const form = result.data;
      setFormData(form.data);
      setFormStatus(form.status);

      // Load template schema from Supabase directly since templates don't have a repository hook yet
      const { data: template } = await supabase
        .from("form_templates")
        .select("name, schema")
        .eq("id", form.templateId)
        .single();

      if (template) {
        setTemplateName(template.name);
        setSections(template.schema?.sections || []);
      }
    } catch {
      Alert.alert("Error", "Network error loading form.");
    }
    setLoading(false);
  }

  function updateField(fieldId: string, value: unknown) {
    setFormData((prev) => ({ ...prev, [fieldId]: value }));
  }

  async function handleSave() {
    if (!id) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    setSaving(true);
    try {
      const result = await formRepository.update(id, { data: formData });
      if (result.success) {
        Alert.alert("Saved", "Form saved successfully.");
      } else {
        Alert.alert("Error", result.error.message);
      }
    } catch {
      Alert.alert("Error", "Failed to save form.");
    }
    setSaving(false);
  }

  async function handleSubmit() {
    if (!id) return;
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    setSaving(true);
    try {
      const result = await formRepository.update(id, { data: formData, status: "completed", submittedAt: new Date() });
      if (result.success) {
        Alert.alert("Submitted", "Form marked as completed.", [{ text: "OK", onPress: () => router.back() }]);
      } else {
        Alert.alert("Error", result.error.message);
      }
    } catch {
      Alert.alert("Error", "Failed to submit form.");
    }
    setSaving(false);
  }

  async function handleExportPDF() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);

    const html = generatePDFHtml(templateName, sections, formData);

    try {
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: `${templateName} - FPL4FLIGHT` });
    } catch {
      Alert.alert("Error", "Failed to generate PDF.");
    }
  }

  async function handleEmailForm() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    const html = generatePDFHtml(templateName, sections, formData);
    try {
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      const isAvailable = await MailComposer.isAvailableAsync();
      if (!isAvailable) {
        Alert.alert("Email Unavailable", "No email client is configured on this device.");
        return;
      }
      await MailComposer.composeAsync({
        subject: `${templateName} - FPL4FLIGHT`,
        body: `Please find attached the completed ${templateName} form.\n\nGenerated by FPL4FLIGHT.`,
        attachments: [uri],
      });
    } catch {
      Alert.alert("Error", "Failed to compose email.");
    }
  }

  const [showPreview, setShowPreview] = useState(false);
  const [showQR, setShowQR] = useState(false);

  if (loading) {
    return (
      <View style={[styles.container, { paddingTop: insets.top, justifyContent: "center", alignItems: "center" }]}>
        <ActivityIndicator size="large" color={colors.brand[600]} />
        <Text style={{ marginTop: spacing.md, color: colors.runway[500] }}>Loading form...</Text>
      </View>
    );
  }

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={20} color={colors.brand[600]} />
        </TouchableOpacity>
        <View style={styles.headerCenter}>
          <Text style={styles.headerTitle} numberOfLines={1}>{templateName}</Text>
          <View style={[styles.statusPill, formStatus === "completed" && styles.statusCompleted]}>
            <Text style={[styles.statusText, formStatus === "completed" && styles.statusTextCompleted]}>
              {formStatus === "completed" ? "Completed" : "Draft"}
            </Text>
          </View>
        </View>
        <TouchableOpacity onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); setShowPreview(true); }} style={styles.saveHeaderBtn}>
          <Ionicons name="eye-outline" size={20} color={colors.brand[600]} />
        </TouchableOpacity>
        <TouchableOpacity onPress={handleExportPDF} style={styles.saveHeaderBtn}>
          <Ionicons name="download-outline" size={20} color={colors.brand[600]} />
        </TouchableOpacity>
        <TouchableOpacity onPress={handleEmailForm} style={styles.saveHeaderBtn}>
          <Ionicons name="mail-outline" size={20} color={colors.brand[600]} />
        </TouchableOpacity>
        <TouchableOpacity onPress={() => setShowQR(true)} style={styles.saveHeaderBtn}>
          <Ionicons name="qr-code-outline" size={20} color={colors.brand[600]} />
        </TouchableOpacity>
        <TouchableOpacity onPress={handleSave} disabled={saving} style={styles.saveHeaderBtn}>
          <Ionicons name="cloud-upload-outline" size={20} color={colors.brand[600]} />
        </TouchableOpacity>
      </View>

      {/* Form Content */}
      <ScrollView
        contentContainerStyle={{ paddingBottom: insets.bottom + 120 }}
        showsVerticalScrollIndicator={false}
        keyboardShouldPersistTaps="handled"
      >
        {sections.map((section, sIdx) => (
          <View key={sIdx} style={styles.sectionCard}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            {section.fields.map((field) => (
              <FieldRenderer
                key={field.id}
                field={field}
                value={formData[field.id]}
                onChange={(v) => updateField(field.id, v)}
                disabled={formStatus === "completed"}
              />
            ))}
          </View>
        ))}
      </ScrollView>

      {/* Bottom Actions */}
      {formStatus !== "completed" && (
        <View style={[styles.bottomBar, { paddingBottom: insets.bottom + spacing.md }]}>
          <PressableScale style={styles.saveDraftBtn} onPress={handleSave} disabled={saving} haptic>
            <Ionicons name="save-outline" size={18} color={colors.runway[700]} />
            <Text style={styles.saveDraftText}>Save Draft</Text>
          </PressableScale>
          <PressableScale style={styles.submitBtn} onPress={handleSubmit} disabled={saving} haptic>
            <Ionicons name="checkmark-circle" size={18} color={colors.white} />
            <Text style={styles.submitText}>Submit</Text>
          </PressableScale>
        </View>
      )}

      {/* Preview Modal — renders exact same HTML as PDF export */}
      <Modal visible={showPreview} animationType="slide" onRequestClose={() => setShowPreview(false)}>
        <View style={{ flex: 1, backgroundColor: colors.white, paddingTop: insets.top }}>
          <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.runway[200] }}>
            <Text style={{ fontSize: fontSize.lg, fontWeight: "700", color: colors.runway[900] }}>Preview</Text>
            <View style={{ flexDirection: "row", gap: spacing.sm }}>
              <TouchableOpacity onPress={handleExportPDF} style={{ width: 36, height: 36, borderRadius: 18, backgroundColor: colors.brand[50], alignItems: "center", justifyContent: "center" }}>
                <Ionicons name="download-outline" size={18} color={colors.brand[600]} />
              </TouchableOpacity>
              <TouchableOpacity onPress={() => setShowPreview(false)} style={{ width: 36, height: 36, borderRadius: 18, backgroundColor: colors.runway[100], alignItems: "center", justifyContent: "center" }}>
                <Ionicons name="close" size={20} color={colors.runway[600]} />
              </TouchableOpacity>
            </View>
          </View>
          <WebView
            originWhitelist={["*"]}
            source={{ html: generatePDFHtml(templateName, sections, formData) }}
            style={{ flex: 1 }}
            scalesPageToFit={true}
          />
        </View>
      </Modal>

      {/* QR Share Modal */}
      <QRShareModal visible={showQR} onClose={() => setShowQR(false)} formId={id ?? ""} formName={templateName} />
    </View>
  );
}

/** Field Renderer */
function FieldRenderer({ field, value, onChange, disabled }: { field: FormField; value: unknown; onChange: (v: unknown) => void; disabled: boolean }) {
  const [showDatePicker, setShowDatePicker] = useState(false);
  const [showTimePicker, setShowTimePicker] = useState(false);
  const [pickerHour, setPickerHour] = useState(8);
  const [pickerMinute, setPickerMinute] = useState(0);
  const [calendarMonth, setCalendarMonth] = useState(new Date());

  const isDateField = field.id.includes("date") || field.label.toLowerCase().includes("date");
  const isTimeField = field.id.includes("time") || field.label.toLowerCase().includes("time");
  const isDateTimeField = field.label.toLowerCase().includes("date/time") || field.label.toLowerCase().includes("date & time");

  const monthNames = MONTH_NAMES;

  // Date/Time field — show both pickers
  if ((isDateField || isDateTimeField) && field.type === "text") {
    return (
      <View style={styles.fieldGroup}>
        <Text style={styles.fieldLabel}>
          {field.label}{field.required && <Text style={styles.requiredStar}> *</Text>}
        </Text>
        <TouchableOpacity
          style={styles.pickerButton}
          onPress={() => { if (!disabled) setShowDatePicker(true); }}
          disabled={disabled}
        >
          <Ionicons name="calendar-outline" size={18} color={colors.brand[600]} />
          <Text style={value ? styles.pickerValueText : styles.pickerPlaceholderText}>
            {typeof value === "string" && value ? value : "Select date..."}
          </Text>
          <Ionicons name="chevron-down" size={16} color={colors.runway[400]} />
        </TouchableOpacity>

        {showDatePicker && (
          <View style={styles.inlineCalendar}>
            <View style={styles.calHeader}>
              <TouchableOpacity onPress={() => setCalendarMonth(new Date(calendarMonth.getFullYear(), calendarMonth.getMonth() - 1, 1))}>
                <Ionicons name="chevron-back" size={20} color={colors.runway[700]} />
              </TouchableOpacity>
                    <Text style={styles.calMonthText}>{MONTH_NAMES[calendarMonth.getMonth()]} {calendarMonth.getFullYear()}</Text>
              <TouchableOpacity onPress={() => setCalendarMonth(new Date(calendarMonth.getFullYear(), calendarMonth.getMonth() + 1, 1))}>
                <Ionicons name="chevron-forward" size={20} color={colors.runway[700]} />
              </TouchableOpacity>
            </View>
            <View style={styles.calWeekRow}>
              {["Su","Mo","Tu","We","Th","Fr","Sa"].map((d) => <Text key={d} style={styles.calWeekDay}>{d}</Text>)}
            </View>
            <View style={styles.calGrid}>
              {getCalendarDays(calendarMonth).map((day, i) => {
                if (!day) return <View key={`e-${i}`} style={styles.calDayEmpty} />;
                const ds = formatDateStr(day);
                const strValue = typeof value === "string" ? value : "";
                const selected = strValue === ds || strValue.startsWith(ds);
                return (
                  <TouchableOpacity key={ds} style={[styles.calDay, selected && styles.calDaySelected]} onPress={() => {
                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                    if (isDateTimeField) {
                      onChange(ds + " ");
                      setShowDatePicker(false);
                      setShowTimePicker(true);
                    } else {
                      onChange(ds);
                      setShowDatePicker(false);
                    }
                  }}>
                    <Text style={[styles.calDayText, selected && styles.calDayTextSelected]}>{day.getDate()}</Text>
                  </TouchableOpacity>
                );
              })}
            </View>
          </View>
        )}

        {showTimePicker && (
          <View style={styles.inlineTimePicker}>
            <Text style={styles.timePickerLabel}>Select Time</Text>
            <View style={styles.timeRow}>
              <View style={styles.timeCol}>
                <TouchableOpacity onPress={() => setPickerHour((pickerHour + 1) % 24)} style={styles.timeArrow}><Ionicons name="chevron-up" size={22} color={colors.runway[600]} /></TouchableOpacity>
                <View style={styles.timeBox}><Text style={styles.timeVal}>{String(pickerHour).padStart(2, "0")}</Text></View>
                <TouchableOpacity onPress={() => setPickerHour((pickerHour - 1 + 24) % 24)} style={styles.timeArrow}><Ionicons name="chevron-down" size={22} color={colors.runway[600]} /></TouchableOpacity>
              </View>
              <Text style={styles.timeColon}>:</Text>
              <View style={styles.timeCol}>
                <TouchableOpacity onPress={() => setPickerMinute((pickerMinute + 5) % 60)} style={styles.timeArrow}><Ionicons name="chevron-up" size={22} color={colors.runway[600]} /></TouchableOpacity>
                <View style={styles.timeBox}><Text style={styles.timeVal}>{String(pickerMinute).padStart(2, "0")}</Text></View>
                <TouchableOpacity onPress={() => setPickerMinute((pickerMinute - 5 + 60) % 60)} style={styles.timeArrow}><Ionicons name="chevron-down" size={22} color={colors.runway[600]} /></TouchableOpacity>
              </View>
            </View>
            <TouchableOpacity style={styles.timeConfirm} onPress={() => {
              const timeStr = `${String(pickerHour).padStart(2, "0")}:${String(pickerMinute).padStart(2, "0")}`;
              const datePrefix = typeof value === "string" && value ? value.trim().split(" ")[0] : formatDateStr(new Date());
              onChange(`${datePrefix} ${timeStr}`);
              setShowTimePicker(false);
            }}>
              <Text style={styles.timeConfirmText}>Confirm</Text>
            </TouchableOpacity>
          </View>
        )}
      </View>
    );
  }

  // Time-only field
  if (isTimeField && !isDateField && field.type === "text") {
    return (
      <View style={styles.fieldGroup}>
        <Text style={styles.fieldLabel}>
          {field.label}{field.required && <Text style={styles.requiredStar}> *</Text>}
        </Text>
        <TouchableOpacity
          style={styles.pickerButton}
          onPress={() => { if (!disabled) setShowTimePicker(true); }}
          disabled={disabled}
        >
          <Ionicons name="time-outline" size={18} color={colors.brand[600]} />
          <Text style={value ? styles.pickerValueText : styles.pickerPlaceholderText}>
            {typeof value === "string" && value ? value : "Select time..."}
          </Text>
          <Ionicons name="chevron-down" size={16} color={colors.runway[400]} />
        </TouchableOpacity>

        {showTimePicker && (
          <View style={styles.inlineTimePicker}>
            <View style={styles.timeRow}>
              <View style={styles.timeCol}>
                <TouchableOpacity onPress={() => setPickerHour((pickerHour + 1) % 24)} style={styles.timeArrow}><Ionicons name="chevron-up" size={22} color={colors.runway[600]} /></TouchableOpacity>
                <View style={styles.timeBox}><Text style={styles.timeVal}>{String(pickerHour).padStart(2, "0")}</Text></View>
                <TouchableOpacity onPress={() => setPickerHour((pickerHour - 1 + 24) % 24)} style={styles.timeArrow}><Ionicons name="chevron-down" size={22} color={colors.runway[600]} /></TouchableOpacity>
              </View>
              <Text style={styles.timeColon}>:</Text>
              <View style={styles.timeCol}>
                <TouchableOpacity onPress={() => setPickerMinute((pickerMinute + 5) % 60)} style={styles.timeArrow}><Ionicons name="chevron-up" size={22} color={colors.runway[600]} /></TouchableOpacity>
                <View style={styles.timeBox}><Text style={styles.timeVal}>{String(pickerMinute).padStart(2, "0")}</Text></View>
                <TouchableOpacity onPress={() => setPickerMinute((pickerMinute - 5 + 60) % 60)} style={styles.timeArrow}><Ionicons name="chevron-down" size={22} color={colors.runway[600]} /></TouchableOpacity>
              </View>
            </View>
            <TouchableOpacity style={styles.timeConfirm} onPress={() => {
              onChange(`${String(pickerHour).padStart(2, "0")}:${String(pickerMinute).padStart(2, "0")}`);
              setShowTimePicker(false);
            }}>
              <Text style={styles.timeConfirmText}>Confirm</Text>
            </TouchableOpacity>
          </View>
        )}
      </View>
    );
  }
  if (field.type === "checkbox") {
    return (
      <View style={styles.checkboxRow}>
        <Switch
          value={!!value}
          onValueChange={onChange}
          disabled={disabled}
          trackColor={{ false: colors.runway[300], true: colors.brand[400] }}
          thumbColor={value ? colors.brand[600] : colors.runway[400]}
        />
        <Text style={[styles.checkboxLabel, !!value && styles.checkboxLabelChecked]}>{field.label}</Text>
        {field.required && <Text style={styles.requiredStar}>*</Text>}
      </View>
    );
  }

  if (field.type === "select" && field.options) {
    return (
      <View style={styles.fieldGroup}>
        <Text style={styles.fieldLabel}>
          {field.label}{field.required && <Text style={styles.requiredStar}> *</Text>}
        </Text>
        <View style={styles.selectRow}>
          {field.options.map((opt) => (
            <TouchableOpacity
              key={opt}
              style={[styles.selectChip, value === opt && styles.selectChipActive]}
              onPress={() => { if (!disabled) { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); onChange(opt); } }}
              disabled={disabled}
            >
              <Text style={[styles.selectChipText, value === opt && styles.selectChipTextActive]}>{opt}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>
    );
  }

  if (field.type === "textarea") {
    return (
      <View style={styles.fieldGroup}>
        <Text style={styles.fieldLabel}>
          {field.label}{field.required && <Text style={styles.requiredStar}> *</Text>}
        </Text>
        <TextInput
          style={[styles.textInput, styles.textArea]}
          value={typeof value === "string" ? value : ""}
          onChangeText={onChange}
          placeholder={field.placeholder || ""}
          placeholderTextColor={colors.runway[300]}
          multiline
          textAlignVertical="top"
          editable={!disabled}
        />
      </View>
    );
  }

  return (
    <View style={styles.fieldGroup}>
      <Text style={styles.fieldLabel}>
        {field.label}{field.required && <Text style={styles.requiredStar}> *</Text>}
      </Text>
      <TextInput
        style={styles.textInput}
        value={typeof value === "string" ? value : ""}
        onChangeText={onChange}
        placeholder={field.placeholder || ""}
        placeholderTextColor={colors.runway[300]}
        keyboardType={field.type === "number" ? "numeric" : "default"}
        editable={!disabled}
      />
    </View>
  );
}

/** Generate PDF HTML — pixel-perfect replica of PNP Plaridel Airport checklist.
 * Uses the exact original document layout with data overlaid at precise positions.
 * The background is the blank form; we just fill in the values.
 */
function generatePDFHtml(title: string, sections: FormSection[], data: Record<string, unknown>): string {
  // Detect CAAP Flight Plan template
  if (title.toLowerCase().includes("caap") || title.toLowerCase().includes("flight plan")) {
    return generateCaapFlightPlanHtml(data);
  }
  // Default: PNP Checklist
  return generatePnpChecklistHtml(title, data);
}

/** CAAP Flight Plan ATS 2019-1 layout */
function generateCaapFlightPlanHtml(data: Record<string, unknown>): string {
  const d = (key: string) => String(data[key] || "");
  const chk = (key: string) => data[key] === "Yes" ? "✓" : "";

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
@page{size:A4 portrait;margin:8mm;}
*{margin:0;padding:0;box-sizing:border-box;}
body{font-family:"Courier New",Courier,monospace;font-size:9px;padding:10px;color:#000;}
.title{font-size:9px;font-weight:bold;margin-bottom:2px;}
.subtitle{text-align:center;font-size:10px;}
.subtitle-bold{text-align:center;font-size:11px;font-weight:bold;}
.form-title{text-align:center;font-size:11px;font-weight:bold;margin:6px 0 8px;text-decoration:underline;}
table{width:100%;border-collapse:collapse;margin-bottom:3px;}
td,th{border:1px solid #000;padding:2px 4px;font-size:9px;vertical-align:top;}
.lbl{font-size:7px;color:#333;}
.val{font-weight:bold;font-size:10px;}
.sec{background:#eee;font-weight:bold;text-align:center;font-size:8px;padding:3px;}
.box{display:inline-block;width:13px;height:13px;border:1px solid #000;text-align:center;font-size:9px;line-height:13px;margin:0 1px;}
.cert{font-size:7.5px;line-height:1.3;text-align:justify;margin:4px 0;padding:4px;border:1px solid #000;}
</style></head><body>
<div class="title">CAAP Form ATS 2019-1</div>
<div class="title">Flight Plan</div>
<div class="subtitle">Republic of the Philippines</div>
<div class="subtitle-bold">CIVIL AVIATION AUTHORITY OF THE PHILIPPINES</div>
<div class="subtitle">Old MIA Rd, Pasay City, Metro Manila 1300</div>
<div class="form-title">FLIGHT PLAN</div>

<table><tr><td class="lbl" style="width:60px">PRIORITY<br><span class="val">&lt;&lt;= FF →</span></td><td class="lbl">ADDRESSEE(S)<br><span class="val">${d("addressees")}</span></td><td style="width:25px" class="lbl">&lt;&lt;=</td></tr></table>

<table><tr><td class="lbl" style="width:110px">DATE OF FILING<br><span class="val">${d("date_of_filing")}</span></td><td class="lbl">→ ORIGINATOR<br><span class="val">${d("originator")}</span></td><td style="width:25px" class="lbl">&lt;&lt;=</td></tr></table>

<table><tr>
<td class="lbl" style="width:70px">3. MESSAGE TYPE<br><span class="val">( ${d("message_type")} )</span></td>
<td class="lbl">7. AIRCRAFT IDENTIFICATION<br><span class="val">${d("aircraft_id")}</span></td>
<td class="lbl" style="width:65px">8. FLIGHT RULES<br><span class="val">${d("flight_rules")}</span></td>
<td class="lbl" style="width:70px">TYPE OF FLIGHT<br><span class="val">${d("type_of_flight")}</span></td>
<td style="width:25px" class="lbl">&lt;&lt;=</td>
</tr></table>

<table><tr>
<td class="lbl" style="width:50px">9. NUMBER<br><span class="val">${d("number_aircraft")}</span></td>
<td class="lbl" style="width:90px">TYPE OF AIRCRAFT<br><span class="val">${d("type_of_aircraft")}</span></td>
<td class="lbl" style="width:20px">/</td>
<td class="lbl" style="width:50px">WAKE TURB.<br><span class="val">${d("wake_turbulence")}</span></td>
<td class="lbl">10. EQUIPMENT<br><span class="val">${d("equipment")}</span></td>
<td class="lbl" style="width:60px">SURV.<br><span class="val">${d("surveillance")}</span></td>
<td style="width:25px" class="lbl">&lt;&lt;=</td>
</tr></table>

<table><tr>
<td class="lbl" style="width:130px">13. DEPARTURE AERODROME<br><span class="val">${d("departure_aerodrome")}</span></td>
<td class="lbl" style="width:70px">TIME<br><span class="val">${d("departure_time")}</span></td>
<td style="width:25px" class="lbl">&lt;&lt;=</td>
</tr></table>

<table><tr>
<td class="lbl" style="width:80px">15. CRUISING SPEED<br><span class="val">${d("cruising_speed")}</span></td>
<td class="lbl" style="width:50px">LEVEL<br><span class="val">${d("level")}</span></td>
<td class="lbl">→ ROUTE<br><span class="val">${d("route")}</span></td>
</tr></table>

<table><tr>
<td class="lbl" style="width:120px">16. DEST. AERODROME<br><span class="val">${d("destination_aerodrome")}</span></td>
<td class="lbl" style="width:70px">TOTAL EET<br><span class="val">${d("total_eet")}</span></td>
<td class="lbl">→ ALTN<br><span class="val">${d("altn_aerodrome")}</span></td>
<td class="lbl">→ 2nd ALTN<br><span class="val">${d("altn_aerodrome_2")}</span></td>
<td style="width:25px" class="lbl">&lt;&lt;=</td>
</tr></table>

<table><tr><td class="lbl">18. OTHER INFORMATION<br><span class="val">${d("other_info")}</span></td></tr></table>

<table><tr><td class="sec">SUPPLEMENTARY INFORMATION (NOT TO BE TRANSMITTED IN FPL MESSAGES)</td></tr></table>

<table><tr>
<td class="lbl">19 ENDURANCE<br>E / <span class="val">${d("endurance_hr")}</span> : <span class="val">${d("endurance_min")}</span></td>
<td class="lbl">→ P / <span class="val">${d("persons_on_board")}</span></td>
<td class="lbl">→ R / UHF <span class="box">${chk("emergency_radio_uhf")}</span> VHF <span class="box">${chk("emergency_radio_vhf")}</span> ELT <span class="box">${chk("emergency_radio_elt")}</span></td>
</tr></table>

<table><tr>
<td class="lbl">SURVIVAL EQUIP → S / POLAR <span class="box">${chk("survival_polar")}</span> DESERT <span class="box">${chk("survival_desert")}</span> MARITIME <span class="box">${chk("survival_maritime")}</span> JUNGLE <span class="box">${chk("survival_jungle")}</span></td>
<td class="lbl">JACKETS J / LIGHT <span class="box">${chk("jackets_light")}</span> FLUORES <span class="box">${chk("jackets_fluores")}</span> UHF <span class="box">${chk("jackets_uhf")}</span> VHF <span class="box">${chk("jackets_vhf")}</span></td>
</tr></table>

<table><tr><td class="lbl">DINGHIES D / NUMBER <span class="val">${d("dinghies_number")}</span> CAPACITY <span class="val">${d("dinghies_capacity")}</span> COVER <span class="box">${chk("dinghies_cover")}</span> COLOUR <span class="val">${d("dinghies_colour")}</span></td><td style="width:25px" class="lbl">&lt;&lt;=</td></tr></table>

<table><tr><td class="lbl">AIRCRAFT COLOUR AND MARKINGS<br>A / <span class="val">${d("aircraft_colour")}</span></td></tr></table>

<table><tr><td class="lbl">REMARKS<br>N / <span class="val">${d("remarks")}</span></td><td style="width:25px" class="lbl">&lt;&lt;=</td></tr></table>

<table><tr><td class="lbl">PILOT IN COMMAND<br>C / <span class="val">${d("pilot_in_command")}</span></td><td style="width:35px" class="lbl">) &lt;&lt;=</td></tr></table>

<table><tr><td class="lbl" style="width:50px">FILED BY</td><td class="val">${d("filed_by")}</td></tr></table>

<div class="cert"><strong>CERTIFICATION</strong><br>This is to certify that the above entries are true and correct and that, pilot-in-command of this aircraft, pledge not to fly over prohibited and restricted areas; will not willfully deviate from the filed flight plan, except when necessary in the interest of safety; will operate only in accordance with existing Civil and Military regulations; and will not operate in any manner inimical to the security of the Republic of the Philippines.</div>

<table><tr>
<td class="lbl"><span class="val">${d("pilot_name_signature")}</span><br>PILOT'S NAME AND SIGNATURE</td>
<td class="lbl"><span class="val">${d("license_no")}</span><br>LICENSE NO., RATING &amp; EXPIRY DATE</td>
</tr></table>

<table><tr><td class="sec" colspan="3">CAAP ACCEPTANCE</td></tr>
<tr><td class="lbl">Received by:</td><td class="lbl">Date/Time Filed</td><td class="lbl">Facility/Airport</td></tr></table>

<p style="text-align:center;font-size:7px;margin-top:4px;">(PLEASE SEE BACK PAGE FOR GUIDANCE AND INSTRUCTION)</p>

<!-- PAGE 2: INSTRUCTIONS & QUICK GUIDE -->
<div style="page-break-before:always;"></div>

<h2 style="text-align:center;font-size:12px;font-weight:bold;text-decoration:underline;margin-bottom:10px;font-family:Times New Roman,serif;">I N S T R U C T I O N S</h2>

<div style="font-family:Times New Roman,serif;font-size:9px;line-height:1.5;margin-bottom:12px;">
<p style="margin-bottom:4px;"><b>1.</b> Accomplish form in Triplicate:</p>
<p style="margin-left:16px;">a) Original (white) to AIS, FSS, TWR or Airport Officer In-Charge</p>
<p style="margin-left:16px;">b) Duplicate (yellow) to pilot in-command</p>
<p style="margin-left:16px;margin-bottom:6px;">c) Triplicate (green) to aircraft owner/operator</p>

<p style="margin-bottom:6px;"><b>2.</b> Complete all items in the Flight Plan form as required using capital letters.</p>

<p style="margin-bottom:6px;"><b>3.</b> Completed flight plan form must be personally filed, faxed or AFTN by the pilot in-command or his duly licensed authorized representative (Licensed Flight Dispatcher) with the appropriate air traffic services unit (AIS, FSS and TWR accordingly) one (1) hour before the EOBT.</p>

<p style="margin-bottom:6px;"><b>4.</b> ERASURE OR ALTERATION IN ACCOMPLISHING THIS FORM IS NOT ALLOWED.</p>

<p style="margin-bottom:6px;"><b>5.</b> Filed flight plan shall be kept for a period of one (1) year and must be made available for references by the appropriate authority.</p>

<p style="margin-bottom:6px;"><b>6.</b> Attach passenger manifest (for general aviation flights).</p>

<p style="margin-bottom:10px;"><b>7.</b> Include client name, postal address with expiry date to operate and contact number in the remarks (for general aviation flights).</p>
</div>

<h2 style="text-align:center;font-size:11px;font-weight:bold;text-decoration:underline;margin-bottom:8px;font-family:Times New Roman,serif;">QUICK GUIDE</h2>

<div style="font-family:Courier New,monospace;font-size:7px;line-height:1.4;columns:3;column-gap:12px;column-rule:1px solid #ccc;">
<p><b>Field 10a</b></p>
<p>N No capabilities</p>
<p>S Standard</p>
<p>A GNSS Landing System</p>
<p>B LPV (APV w/SBAS)</p>
<p>C LORAN C</p>
<p>D DME</p>
<p>E1 FMC WPR</p>
<p>E2 D-FIS</p>
<p>E3 PDC</p>
<p>F ADF</p>
<p>G GNSS</p>
<p>H HF RTF</p>
<p>I INS</p>
<p>J1 VDL Mode 2</p>
<p>J2 HFDL</p>
<p>J3 VDL Mode A</p>
<p>J4 VDL Mode 2</p>
<p>J5 Satcom Inmarsat</p>
<p>J6 Satcom MTSAT</p>
<p>J7 Satcom Iridium</p>
<p>K MLS</p>
<p>L ILS</p>
<p>M1 Inmarsat</p>
<p>M2 MTSAT</p>
<p>M3 Iridium</p>
<p>O VOR</p>
<p>P1 CPDLC RCP 400</p>
<p>P2 CPDLC RCP240</p>
<p>P3 Sat Voice RCP400</p>
<p>R PBN</p>
<p>T TACAN</p>
<p>U UHF RTF</p>
<p>V VHF RTF</p>
<p>W RVSM</p>
<p>X MNPS</p>
<p>Y 8.33 kHz VHF</p>
<p>Z Other Cap.</p>
<p>&nbsp;</p>
<p><b>Notes:</b></p>
<p>1. Filing R requires PBN/ in Field 18</p>
<p>2. Filing Z requires NAV, COM, or DAT in Field 18</p>
<p>3. Standard = VOR, VHF, ILS</p>
<p>4. File in order shown</p>
<p>&nbsp;</p>
<p><b>Field 10b</b></p>
<p>N No capability</p>
<p><b>Transponder:</b></p>
<p>A Mode A</p>
<p>C Mode A and C</p>
<p>S Mode S, ACID+Alt</p>
<p>P Mode S, Alt, no ACID</p>
<p>I Mode S, ACID, no Alt</p>
<p>X Mode S, no ACID/Alt</p>
<p><b>ADS-B:</b></p>
<p>B1 1090 MHz out</p>
<p>B2 1090 MHz out+in</p>
<p>U1 UAT out+in</p>
<p>U2 UAT out+in</p>
<p>V1 VDL Mode 4 out</p>
<p>V2 VDL Mode 4 out+in</p>
<p><b>ADS-C:</b></p>
<p>D1 ADS-C FANS-1/A</p>
<p>G1 ADS-C ATN</p>
<p>&nbsp;</p>
<p><b>Field 18 Other Info</b></p>
<p><b>(File in this order)</b></p>
<p>STS/ Special Handling</p>
<p>PBN/ Perf Based Nav</p>
<p>NAV/ Other Nav Cap</p>
<p>COM/ Other Comm Cap</p>
<p>DAT/ Other Data App</p>
<p>SUR/ Other Surveillance</p>
<p>DEP/ Non-std Departure</p>
<p>DEST/ Non-std Destination</p>
<p>DOF/ Date of Flight</p>
<p>REG/ Registration</p>
<p>EET/ Estimated Elapsed</p>
<p>TYP/ Non-std AC Type</p>
<p>CODE/ 24-bit address</p>
<p>DLE/ Delay at a fix</p>
<p>OPR/ Operator</p>
<p>ORGN/ FPL Originator</p>
<p>PER/ Perf Category</p>
<p>ALTN/ Non-std Alternates</p>
<p>RALT/ Enroute Alternate</p>
<p>TALT/ Takeoff Alternate</p>
<p>RIF/ Route to revised Dest</p>
<p>RMK/ Remarks</p>
<p>&nbsp;</p>
<p><b>PBN/ (8 max)</b></p>
<p>A1 RNAV10 [RNP10]</p>
<p>B1-B6 RNAV 5</p>
<p>C1-C4 RNAV 2</p>
<p>D1-D4 RNAV 1</p>
<p>L1 RNP 4</p>
<p>O1-O3 RNP 1</p>
<p>S1 RNP APCH</p>
<p>S2 RNP APCH w/BARO</p>
<p>T1 RNP AR w/RF</p>
<p>T2 RNP AR w/o RF</p>
<p>&nbsp;</p>
<p><b>SUR/</b></p>
<p>RSP180</p>
<p>RSP400</p>
</div>

</body></html>`;
}

/** PNP Plaridel Airport Checklist (Arrival / Pre-Flight) */
function generatePnpChecklistHtml(title: string, data: Record<string, unknown>): string {
  const q1 = data["q1"] === "COMPLIED" ? "✓" : "";
  const q2 = data["q2"] === "COMPLIED" ? "✓" : "";
  const q3 = data["q3"] === "COMPLIED" ? "✓" : "";
  const q4 = data["q4"] === "COMPLIED" ? "✓" : "";
  const q5 = data["q5"] === "COMPLIED" ? "✓" : "";
  const q6 = data["q6"] === "COMPLIED" ? "✓" : "";
  const q7 = data["q7"] === "COMPLIED" ? "✓" : "";
  const q8 = data["q8"] === "COMPLIED" ? "✓" : "";
  const q9 = data["q9"] === "COMPLIED" ? "✓" : "";
  const q1r = data["q1r"] || "";
  const q2r = data["q2r"] || "";
  const q3r = data["q3r"] || "";
  const q4r = data["q4r"] || "";
  const q5r = data["q5r"] || "";
  const q6r = data["q6r"] || "";
  const q7r = data["q7r"] || "";
  const q8r = data["q8r"] || "";
  const q9r = data["q9r"] || "";
  const acId = data["ac_id"] || "";
  const dateTime = data["date_time"] || "";
  const acType = data["ac_type"] || "";
  const itinerary = data["itinerary"] || "";
  const pax = data["pax"] || "";
  const pilot = data["pilot"] || "";
  const duty = data["duty"] || "";

  const isArrival = title.toLowerCase().includes("arrival");
  const formTitle = isArrival ? "ARRIVAL FLIGHT INSPECTION CHECKLIST" : "PRE - FLIGHT INSPECTION CHECKLIST";

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
@page{size:A4 portrait;margin:10mm;}
*{margin:0;padding:0;box-sizing:border-box;}
body{font-family:"Times New Roman",Times,serif;font-size:9.5px;padding:12px 18px;color:#000;line-height:1.2;}

/* HEADER */
.hdr{width:100%;display:table;margin-bottom:6px;}
.hdr-logo{display:table-cell;width:60px;vertical-align:middle;text-align:center;}
.hdr-logo img{width:50px;height:50px;}
.hdr-center{display:table-cell;text-align:center;vertical-align:middle;padding:0 6px;}
.hdr-center p{margin:0;padding:0;}
.h-rp{font-size:10px;}
.h-npc{font-size:10px;font-weight:bold;}
.h-pnp{font-size:9px;font-weight:bold;}
.h-asu{font-size:11px;font-weight:bold;}
.h-paps{font-size:11px;font-weight:bold;}
.h-addr{font-size:8.5px;font-style:italic;}
.h-title{font-size:10.5px;font-weight:bold;margin-top:8px;margin-bottom:10px;}

/* TABLES */
table{width:100%;border-collapse:collapse;margin-bottom:4px;}
th,td{border:1px solid #000;padding:2px 4px;vertical-align:top;font-size:9px;text-align:left;}
th{font-weight:bold;text-align:center;font-size:9px;}
.col-c{width:52px;text-align:center;font-weight:bold;font-size:12px;}
.col-r{width:82px;}
.col-d{line-height:1.3;}

/* FLIGHT DETAILS */
.fd{margin-top:6px;font-size:9.5px;}
.fd-row{display:flex;align-items:flex-end;margin-bottom:4px;}
.fd-label{min-width:155px;font-size:9.5px;}
.fd-val{flex:1;border-bottom:1px solid #000;min-height:14px;padding-left:4px;font-size:9.5px;}
.fd-row-tall{margin-bottom:18px;}
</style></head><body>

<div class="hdr">
<div class="hdr-logo"><img src="" alt="PNP"/></div>
<div class="hdr-center">
<p class="h-rp">Republic of the Philippines</p>
<p class="h-npc">NATIONAL POLICE COMMISSION</p>
<p class="h-pnp">PHILIPPINE NATIONAL POLICE, AVIATION SECURITY GROUP</p>
<p class="h-asu">AVIATION SECURITY UNIT 3</p>
<p class="h-paps">PLARIDEL AIRPORT POLICE STATION</p>
<p class="h-addr">Plaridel Airport, Brgy. Lumang Bayan, Plaridel, Bulacan</p>
</div>
<div class="hdr-logo"><img src="" alt="NAPOLCOM"/></div>
</div>
<p class="h-title">${formTitle}</p>
</div>

<!-- AIRCRAFT SECTION -->
<table>
<tr><th class="col-c">COMPLIED</th><th class="col-d">AIRCRAFT</th><th class="col-r">REMARKS</th></tr>
<tr><td class="col-c">${q1}</td><td class="col-d">1. Visually inspected the interiors of the aircraft for any alterations out of the ordinary.</td><td class="col-r">${q1r}</td></tr>
<tr><td class="col-c">${q2}</td><td class="col-d">2. Check for the presence of hazardous/dangerous and prohibited items. (firearms, chemicals, illegal drugs)</td><td class="col-r">${q2r}</td></tr>
<tr><td class="col-c">${q3}</td><td class="col-d">3. Check the cargo bay and make sure that the baggage's are not yet loaded to the aircraft before inspection.<br>(Note: Coordinate with concerned agencies for international flights)</td><td class="col-r">${q3r}</td></tr>
</table>

<!-- BAGGAGE/LUGGAGE/CARGO SECTION -->
<table>
<tr><th class="col-c">COMPLIED</th><th class="col-d">BAGGAGE/LUGGAGE/CARGO</th><th class="col-r">REMARKS</th></tr>
<tr><td class="col-c">${q4}</td><td class="col-d">4. Monitor the conduct of disembarkation of luggage, baggage and cargo from the aircraft.</td><td class="col-r">${q4r}</td></tr>
<tr><td class="col-c">${q5}</td><td class="col-d">5. Immediately isolate suspected baggage/cargo for manual inspection by GA/AW operator in the presence of the owner.<br>(Note: Refers to the OTS Updated list of SRIs)</td><td class="col-r">${q5r}</td></tr>
<tr><td class="col-c">${q6}</td><td class="col-d">6. Take appropriate action on the discrepancies on the documents and intercepted SRI/s.<br>(Note: Coordinate with concerned agencies for international flights)</td><td class="col-r">${q6r}</td></tr>
</table>

<!-- PILOT'S, CREW & PASSENGERS SECTION -->
<table>
<tr><th class="col-c">COMPLIED</th><th class="col-d">PILOT'S, CREW &amp;PASSENGERS</th><th class="col-r">REMARKS</th></tr>
<tr><td class="col-c">${q7}</td><td class="col-d">${isArrival ? "1" : "7"}. Positive identification shall be conducted on pilot/s, crew/s and passengers during boarding with the flight manifest as basis.</td><td class="col-r">${q7r}</td></tr>
<tr><td class="col-c">${q8}</td><td class="col-d">${isArrival ? "2" : "8"}. Profiling of pilot/s, crew/s and passengers.</td><td class="col-r">${q8r}</td></tr>
<tr><td class="col-c">${q9}</td><td class="col-d">${isArrival ? "3" : "9"}. Take appropriate action on the discrepancies on the documents and intercepted SRI/s.<br>(Note: Coordinate with concerned agencies for international flights)</td><td class="col-r">${q9r}</td></tr>
</table>

<!-- FLIGHT DETAILS -->
<div class="fd">
<div class="fd-row"><span class="fd-label">Aircraft Identification:</span><span class="fd-val">${acId}</span></div>
<div class="fd-row"><span class="fd-label">Date/Time:</span><span class="fd-val">${dateTime}</span></div>
<div class="fd-row"><span class="fd-label">Type of aircraft:</span><span class="fd-val">${acType}</span></div>
<div class="fd-row"><span class="fd-label">Itinerary:</span><span class="fd-val">${itinerary}</span></div>
<div class="fd-row fd-row-tall"><span class="fd-label">Name of Passengers &amp; Nationality:</span><span class="fd-val">${pax}</span></div>
<div class="fd-row"><span class="fd-label">Name of Pilot &amp; Nationality:</span><span class="fd-val">${pilot}</span></div>
<div class="fd-row"><span class="fd-label">Duty Ramp/Gen Av:</span><span class="fd-val">${duty}</span></div>
</div>

</body></html>`;
}


const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.runway[50] },
  header: { flexDirection: "row", alignItems: "center", paddingHorizontal: spacing.md, paddingVertical: 12, backgroundColor: colors.white, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.runway[200] },
  backBtn: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
  headerCenter: { flex: 1, alignItems: "center" },
  headerTitle: { fontSize: fontSize.base, fontWeight: "700", color: colors.runway[900] },
  statusPill: { marginTop: 4, backgroundColor: colors.amber[50], paddingHorizontal: 10, paddingVertical: 2, borderRadius: 8 },
  statusCompleted: { backgroundColor: colors.green[50] },
  statusText: { fontSize: 10, fontWeight: "700", color: colors.amber[600] },
  statusTextCompleted: { color: colors.green[600] },
  saveHeaderBtn: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
  // Sections
  sectionCard: { backgroundColor: colors.white, marginHorizontal: spacing.md, marginTop: spacing.md, borderRadius: 16, padding: spacing.lg, shadowColor: colors.black, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 6, elevation: 1 },
  sectionTitle: { fontSize: fontSize.base, fontWeight: "700", color: colors.brand[600], marginBottom: spacing.lg, letterSpacing: 0.3 },
  // Fields
  fieldGroup: { marginBottom: spacing.md },
  fieldLabel: { fontSize: fontSize.sm, fontWeight: "600", color: colors.runway[700], marginBottom: 8 },
  requiredStar: { color: colors.red[500] },
  textInput: { backgroundColor: colors.runway[50], borderWidth: 1.5, borderColor: colors.runway[200], borderRadius: 12, paddingHorizontal: spacing.md, paddingVertical: 14, fontSize: fontSize.base, color: colors.runway[900] },
  textArea: { height: 80, textAlignVertical: "top" },
  // Checkbox
  checkboxRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.runway[100] },
  checkboxLabel: { flex: 1, fontSize: fontSize.sm, color: colors.runway[600] },
  checkboxLabelChecked: { color: colors.runway[900], fontWeight: "600" },
  // Select
  selectRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  selectChip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 20, backgroundColor: colors.runway[100], borderWidth: 1.5, borderColor: colors.runway[200] },
  selectChipActive: { backgroundColor: colors.brand[600], borderColor: colors.brand[600] },
  selectChipText: { fontSize: fontSize.sm, fontWeight: "600", color: colors.runway[500] },
  selectChipTextActive: { color: colors.white },
  // Bottom bar
  bottomBar: { position: "absolute", bottom: 0, left: 0, right: 0, flexDirection: "row", gap: spacing.sm, paddingHorizontal: spacing.md, paddingTop: spacing.md, backgroundColor: colors.white, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.runway[200] },
  saveDraftBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 14, borderRadius: 12, backgroundColor: colors.runway[100] },
  saveDraftText: { fontSize: fontSize.sm, fontWeight: "600", color: colors.runway[700] },
  submitBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 14, borderRadius: 12, backgroundColor: colors.brand[600], shadowColor: colors.brand[600], shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 3 },
  submitText: { fontSize: fontSize.sm, fontWeight: "700", color: colors.white },
  // Picker styles
  pickerButton: { flexDirection: "row", alignItems: "center", backgroundColor: colors.runway[50], borderWidth: 1.5, borderColor: colors.runway[200], borderRadius: 12, paddingHorizontal: spacing.md, paddingVertical: 14, gap: spacing.sm },
  pickerValueText: { flex: 1, fontSize: fontSize.base, fontWeight: "600", color: colors.runway[900] },
  pickerPlaceholderText: { flex: 1, fontSize: fontSize.base, color: colors.runway[300] },
  // Inline calendar
  inlineCalendar: { backgroundColor: colors.white, borderRadius: 14, padding: spacing.md, marginTop: spacing.sm, borderWidth: 1, borderColor: colors.runway[200] },
  calHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.sm },
  calMonthText: { fontSize: fontSize.sm, fontWeight: "700", color: colors.runway[900] },
  calWeekRow: { flexDirection: "row", marginBottom: 4 },
  calWeekDay: { flex: 1, textAlign: "center", fontSize: 10, fontWeight: "600", color: colors.runway[400] },
  calGrid: { flexDirection: "row", flexWrap: "wrap" },
  calDayEmpty: { width: "14.28%", height: 36 },
  calDay: { width: "14.28%", height: 36, alignItems: "center", justifyContent: "center", borderRadius: 18 },
  calDaySelected: { backgroundColor: colors.brand[600] },
  calDayText: { fontSize: fontSize.sm, color: colors.runway[800] },
  calDayTextSelected: { color: colors.white, fontWeight: "700" },
  // Inline time picker
  inlineTimePicker: { backgroundColor: colors.white, borderRadius: 14, padding: spacing.md, marginTop: spacing.sm, borderWidth: 1, borderColor: colors.runway[200], alignItems: "center" },
  timePickerLabel: { fontSize: fontSize.sm, fontWeight: "600", color: colors.runway[700], marginBottom: spacing.sm },
  timeRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, marginBottom: spacing.md },
  timeCol: { alignItems: "center" },
  timeArrow: { padding: 6 },
  timeBox: { width: 56, height: 56, borderRadius: 12, backgroundColor: colors.runway[50], borderWidth: 1, borderColor: colors.runway[200], alignItems: "center", justifyContent: "center" },
  timeVal: { fontSize: 24, fontWeight: "800", color: colors.runway[900] },
  timeColon: { fontSize: 24, fontWeight: "800", color: colors.runway[400] },
  timeConfirm: { backgroundColor: colors.brand[600], paddingHorizontal: spacing.xl, paddingVertical: 10, borderRadius: 10, width: "100%", alignItems: "center" },
  timeConfirmText: { fontSize: fontSize.sm, fontWeight: "700", color: colors.white },
});
